version: "3"
services:
  notebook:
    # image: jupyter/scipy-notebook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    # environment:
    #   - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/workspace
      - ./requirements:/requirements
    command: jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''
